# image will be published to ghcr.io/<user>/<name>
name: fedora-atomic-container
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: fonts
    fonts:
      nerd-fonts:
        # cosmic desktop environment
        - FireMono
        - FiraCode
        # personal fonts
        - GeistMono
        - Lilex
        
  - type: script
    snippets:
      # cosmic desktop environment
      - 'wget https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-$(rpm -E %fedora)/ryanabx-cosmic-epoch-fedora-$(rpm -E %fedora).repo -O /etc/yum.repos.d/_copr_ryanabx-cosmic.repo'
      # personal repositories
      - 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://downloads.1password.com/linux/keys/1password.asc" > /etc/yum.repos.d/1password.repo'

  - type: rpm-ostree
    repos:
      # personal repositories
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo
    keys:
      - https://downloads.1password.com/linux/keys/1password.asc
    optfix:
      - 1Password
    install:
      # cosmic desktop environment
      - cosmic-desktop
      - cosmic-idle
      - NetworkManager-tui
      - NetworkManager-openvpn
      - power-profiles-daemon
      - gnome-keyring
      # personal - security and backup
      - 1password
      - clamav
      - clamav-freshclam
      - fail2ban
      - pam_yubico
      - ykocli
      - yubico-piv-tool
      - borgbackup
      - syncthing
      # personal - fonts
      - cascadia-fonts-all
      - fontawesome-fonts-all
      - jetbrains-mono-fonts-all
      - ibm-plex-mono-fonts
      - liberation-fonts
      # personal - virtualization
      - docker
      - libvirt
      - qemu
      - swtpm-tools
      - virt-manager
      - virtio-win
      - tuned
      # personal - extra
      - starship
      - helix
      - neovim
      - inxi
      - fastfetch
      - chromium
      - fzf
      - sshfs
      - dislocker
      - rustup
      - cargo
      - pinentry-gnome3
      - pinentry-qt
      - pinentry-tty
      - pinentry-emacs
    remove:

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      # personal system flatpaks
        - com.github.wwmm.easyeffects
        - hu.irl.cameractrls
        - org.gnome.World.PikaBackup
        - com.brave.Browser
        - io.github.zen_browser.zen
        - io.github.ungoogled_software.ungoogled_chromium
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
    user:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      # personal user flatpaks
        - com.obsproject.Studio
        - io.freetubeapp.FreeTube
      remove:

  - type: bling
    install:
      # personal bling
      - 1password

  - type: systemd
    system:
      enabled:
        # cosmic desktop environment
        - power-profiles-daemon.service
        # personal services
        - rpm-ostreed-automatic.timer
        - clamav-freshclam.service
        - fail2ban.service
        - tuned.service
        - docker.service
        - fstrim.timer
      disable:
        - cosmic-greeter.service
        - cosmic-greeter.daemon.service

  - type: script
    scripts:
      # personal scripts
      - settings.sh
      - services.sh
    snippets:
      # personal extras
      - "cargo install --locked blue-build"
      - "bluebuild completions bash | tee /usr/share/bash-completion/completions/bluebuild"
    
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

