# image will be published to ghcr.io/<user>/<name>
name: fedora-atomic-container
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono
        - LiberationMono
        - GeistMono
         
  - type: script
    snippets:
      # install repos
      - 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://downloads.1password.com/linux/keys/1password.asc" > /etc/yum.repos.d/1password.repo'
      - "wget https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo -O /etc/yum.repos.d/virtio-win.repo"

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    keys:
      - https://downloads.1password.com/linux/keys/1password.asc
    optfix:
      - 1Password
    install:
      # security and backup
      - 1password
      - clamav
      - clamav-freshclam
      - fail2ban
      - pam_yubico
      - ykocli
      - yubico-piv-tool
      - borgbackup
      - syncthing
      # fonts
      - cascadia-fonts-all
      - fontawesome-fonts-all
      - ibm-plex-mono-fonts
      - jetbrains-mono-fonts-all
      - liberation-fonts
      # network
      - sshfs
      - NetworkManager-tui
      # virtualization
      - docker
      - libvirt
      - qemu
      - swtpm-tools
      - tuned
      - virt-manager
      - virtio-win
      # gnome extra
      - adw-gtk3-theme
      - gnome-extensions-app
      - gnome-screenshot
      - gnome-shell-extension-pop-shell
      - gnome-tweaks
      # extra
      - starship
      - helix
      - neovim
      - fastfetch
      - chromium
      - fzf
      - dislocker
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.github.wwmm.easyeffects
        - hu.irl.cameractrls
        - org.gnome.World.PikaBackup
        - com.brave.Browser
        - io.github.zen_browser.zen
        - io.github.ungoogled_software.ungoogled_chromium
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog
    user:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.obsproject.Studio
        - io.freetubeapp.FreeTube
        # - org.gimp.GIMP
        # - org.kde.krita
        # - fr.handbrake.ghb
        # - io.github.nokse22.asciidraw
        # - org.freecadweb.FreeCAD
        # - com.valvesoftware.SteamLink
        # - io.podman_desktop.PodmanDesktop
        # - org.wezfurlong.wezterm
      remove:
      # - org.gnome.eog

  - type: bling
    install:
      - 1password

  - type: systemd
    system:
      enabled:
        - clamav-freshclam.service
        - fail2ban.service
        - tuned.service
        - docker.service
        - fstrim.timer
        # - virtinterfaced-admin.socket
        # - virtinterfaced-ro.socket
        # - virtinterfaced.service
        # - virtinterfaced.socket
        # - virtlockd-admin.socket
        # - virtlockd.service
        # - virtlockd.socket
        # - virtlogd-admin.socket
        # - virtlogd.service
        # - virtlogd.socket
        # - virtlxcd-admin.socket
        # - virtlxcd-ro.socket
        # - virtlxcd.service
        # - virtlxcd.socket
        # - virtnetworkd-admin.socket
        # - virtnetworkd-ro.socket
        # - virtnetworkd.service
        # - virtnetworkd.socket
        # - virtnodedevd-admin.socket
        # - virtnodedevd-ro.socket
        # - virtnodedevd.service
        # - virtnodedevd.socket
        # - virtnwfilterd-admin.socket
        # - virtnwfilterd-ro.socket
        # - virtnwfilterd.service
        # - virtnwfilterd.socket
        # - virtproxyd-admin.socket
        # - virtproxyd-ro.socket
        # - virtproxyd.service
        # - virtproxyd.socket
        # - virtproxyd-tcp.socket
        # - virtproxyd-tls.socket
        # - virtqemud-admin.socket
        # - virtqemud-ro.socket
        # - virtqemud.service
        # - virtqemud.socket
        # - virtsecretd-admin.socket
        # - virtsecretd-ro.socket
        # - virtsecretd.service
        # - virtsecretd.socket
        # - virtstoraged-admin.socket
        # - virtstoraged-ro.socket
        # - virtstoraged.service
        # - virtstoraged.socket
        # - virtvboxd-admin.socket
        # - virtvboxd-ro.socket
        # - virtvboxd.service
        # - virtvboxd.socket
        # - virtxend-admin.socket
        # - virtxend-ro.socket
        # - virtxend.service
        # - virtxend.socket

  - type: script
    scripts:
      - settings.sh
      - services.sh
    snippets:
      - "cargo install --locked blue-build"
      - "bluebuild completions bash | tee /usr/share/bash-completion/completions/bluebuild"

    
  # - type: gnome-extensions
  #   install:
      # - Tiling Assistant # Case sensitive name of the extention (https://extensions.gnome.org/)

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

