# image will be published to ghcr.io/<user>/<name>
name: fedora-atomic-container
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - JetBrainsMono
        - LiberationMono
        - GeistMono
         
  - type: script
    snippets:
      # install repos
      - sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://downloads.1password.com/linux/keys/1password.asc" > /etc/yum.repos.d/1password.repo'
      - "wget https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo -O /etc/yum.repos.d/virtio-win.repo"

      # create standard /mnt directories
      - mkdir -p /var/mnt/{sshfsmnt_,localmnt_}{1..5} 
      - chmod 777 /var/mnt/{sshfsmnt_,localmnt_}{1..5} 
      - touch /var/mnt/{sshfsmnt_,localmnt_}{1..5}/no_mount
      - mkdir -p /var/mnt/bitlockr_{1..2}
      - chmod 777 /var/mnt/bitlockr_{1..2}
      - touch /var/mnt/bitlockr_{1..2}/no_mount

      # create standard $HOME directories
      - mkdir -p "$HOME"/.ssh/keys
      - mkdir -p "$HOME"/.gnupg
      - mkdir -p "$HOME"/Appimages
      - mkdir -p "$HOME"/Miscellaneous
      - mkdir -p "$HOME"/Mounts
      - mkdir -p "$HOME"/Security
      - mkdir -p "$HOME"/Workbench

      # configure GNOME settings
      - gsettings set org.gnome.desktop.interface font-name "Cascadia Mono 11"
      - gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
      - gsettings set org.gnome.desktop.peripherals.touchpad tap-and-drag-lock true

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # security and backup
      - 1password
      - clamav
      - clamav-freshclam
      - fail2ban
      - pam_yubico
      - ykocli
      - yubico-piv-tool
      - borgbackup
      - syncthing
      # fonts
      - cascadia-fonts-all
      - fontawesome-fonts-all
      - ibm-plex-mono-fonts
      - jetbrains-mono-fonts-all
      - liberation-fonts
      # network
      - sshfs
      - NetworkManager-tui
      # virtualization
      - docker
      - libvirt
      - qemu
      - swtpm-tools
      - tuned
      - virt-manager
      - virtio-win
      # gnome extra
      - adw-gtk3-theme
      - gnome-extensions-app
      - gnome-screenshot
      - gnome-shell-extension-pop-shell
      - gnome-tweaks
      # extra
      - starship
      - helix
      - neovim
      - fastfetch
      - chromium
      - fzf
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - io.podman_desktop.PodmanDesktop
        - com.obsproject.Studio
        - org.gimp.GIMP
        - org.kde.krita
        - fr.handbrake.ghb
        - io.github.nokse22.asciidraw
        - com.github.wwmm.easyeffects
        - org.freecadweb.FreeCAD
        - io.freetubeapp.FreeTube
        - org.gnome.World.PikaBackup
        - com.brave.Browser
        - com.valvesoftware.SteamLink
        - io.github.zen_browser.zen
        - hu.irl.cameractrls
        - org.wezfurlong.wezterm
        - io.github.ungoogled_software.ungoogled_chromium
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

